/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.pDL1.impl;

import fr.enseeiht.pDL1.PDL1Package;
import fr.enseeiht.pDL1.ProcessElement;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Process Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProcessElementImpl extends MinimalEObjectImpl.Container implements ProcessElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL1Package.Literals.PROCESS_ELEMENT;
  }

} //ProcessElementImpl
