/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl.ui.contentassist;

import fr.enseeiht.simplepdl.ui.contentassist.AbstractSimplePDLDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SimplePDLDSLProposalProvider extends AbstractSimplePDLDSLProposalProvider {
}
