/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht;

import fr.enseeiht.PDL1StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PDL1StandaloneSetup extends PDL1StandaloneSetupGenerated {
  public static void doSetup() {
    PDL1StandaloneSetup _pDL1StandaloneSetup = new PDL1StandaloneSetup();
    _pDL1StandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
