/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht;

import fr.enseeiht.AbstractPDL1RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PDL1RuntimeModule extends AbstractPDL1RuntimeModule {
}
