/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.scoping;

import fr.enseeiht.scoping.AbstractPDL1ScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PDL1ScopeProvider extends AbstractPDL1ScopeProvider {
}
