/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.validation;

import fr.enseeiht.validation.AbstractPDL2Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PDL2Validator extends AbstractPDL2Validator {
}
