/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.ui;

import com.google.inject.Injector;
import fr.enseeiht.pdl2.ui.internal.Pdl2Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PDL2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Pdl2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Pdl2Activator.getInstance().getInjector(Pdl2Activator.FR_ENSEEIHT_PDL2);
	}
	
}
