/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SimplePDLDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/enseeiht/simplepdl/parser/antlr/internal/InternalSimplePDLDSL.tokens");
	}
}
