/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl.parser.antlr;

import com.google.inject.Inject;
import fr.enseeiht.simplepdl.parser.antlr.internal.InternalSimplePDLDSLParser;
import fr.enseeiht.simplepdl.services.SimplePDLDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SimplePDLDSLParser extends AbstractAntlrParser {

	@Inject
	private SimplePDLDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSimplePDLDSLParser createParser(XtextTokenStream stream) {
		return new InternalSimplePDLDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Process";
	}

	public SimplePDLDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SimplePDLDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
