/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.ui;

import com.google.inject.Injector;
import fr.enseeiht.pdl1.ui.internal.Pdl1Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PDL1ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Pdl1Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Pdl1Activator.getInstance().getInjector(Pdl1Activator.FR_ENSEEIHT_PDL1);
	}
	
}
