/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.ui;

import fr.enseeiht.ui.AbstractPDL2UiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PDL2UiModule extends AbstractPDL2UiModule {
  public PDL2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
