/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSimplePDLDSLScopeProvider extends DelegatingScopeProvider {
}
