/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.ui.tests;

import com.google.inject.Injector;
import fr.enseeiht.pdl2.ui.internal.Pdl2Activator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class PDL2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Pdl2Activator.getInstance().getInjector("fr.enseeiht.PDL2");
	}

}
