/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPDL1ScopeProvider extends DelegatingScopeProvider {
}
