/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl.ui.tests;

import com.google.inject.Injector;
import fr.enseeiht.simplepdl.txt.ui.internal.TxtActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class SimplePDLDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TxtActivator.getInstance().getInjector("fr.enseeiht.simplepdl.SimplePDLDSL");
	}

}
