/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractPDL1Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.enseeiht.pDL1.PDL1Package.eINSTANCE);
		return result;
	}
	
}
