/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl.validation;

import fr.enseeiht.simplepdl.validation.AbstractSimplePDLDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SimplePDLDSLValidator extends AbstractSimplePDLDSLValidator {
}
