/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl.ui;

import com.google.inject.Injector;
import fr.enseeiht.simplepdl.txt.ui.internal.TxtActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimplePDLDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TxtActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TxtActivator.getInstance().getInjector(TxtActivator.FR_ENSEEIHT_SIMPLEPDL_SIMPLEPDLDSL);
	}
	
}
