/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl;

import fr.enseeiht.simplepdl.AbstractSimplePDLDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SimplePDLDSLRuntimeModule extends AbstractSimplePDLDSLRuntimeModule {
}
