/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl;

import fr.enseeiht.simplepdl.SimplePDLDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SimplePDLDSLStandaloneSetup extends SimplePDLDSLStandaloneSetupGenerated {
  public static void doSetup() {
    SimplePDLDSLStandaloneSetup _simplePDLDSLStandaloneSetup = new SimplePDLDSLStandaloneSetup();
    _simplePDLDSLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
