/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht;

import fr.enseeiht.PDL2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PDL2StandaloneSetup extends PDL2StandaloneSetupGenerated {
  public static void doSetup() {
    PDL2StandaloneSetup _pDL2StandaloneSetup = new PDL2StandaloneSetup();
    _pDL2StandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
