/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl.ui;

import fr.enseeiht.simplepdl.ui.AbstractSimplePDLDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SimplePDLDSLUiModule extends AbstractSimplePDLDSLUiModule {
  public SimplePDLDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
