import modele.*;
import afficheurs.*;
import controleurs.*;

public class AutoTamponneuse {

	/**
	  * AUTOGENERATED CLASS
	  * Do not modify the code
	  * Please use toJava.mtl inside an Acceleo Project
	  */

	public static void main(String[] args) {
		/**
		 * Init all elements
		 */
		// Init Jeu
		Jeu autoTamponneuse = new Jeu("AutoTamponneuse");
		// Init Composants
		Territoire fete = new Territoire("Fete");
		Explorateur enfant = new Explorateur("Enfant");
		Lieu parents = new Lieu("Parents");
		Lieu manege = new Lieu("Manege");
		Lieu maison = new Lieu("Maison");
		Chemin bonheur = new Chemin("Bonheur");
		Chemin tristesse = new Chemin("Tristesse");
		Chemin retour = new Chemin("Retour");
		Personne vendeur = new Personne("Vendeur");
		Choix vendre = new Choix("Vendre");
		Choix finVendre = new Choix("FinVendre");
		Action composte = new Action("Composte");
		ObjetElementaire billet = new ObjetElementaire("Billet");
		ObjetElementaire plaisir = new ObjetElementaire("Plaisir");
		Condition unBillet = new Condition("UnBillet");
		Condition unPlaisir = new Condition("UnPlaisir");
		
		// Init Dependencies
		// Init Objets
		Objet billet1 = new Objet();
		Objet plaisir1 = new Objet();
		
		// Init Possessions
		Objet plaisir1Objet = plaisir1;
		Objet billet1Objet = billet1;
		
		// Init PossessionsConditionnees
		PossessionConditionnee plaisir1ObjetPossessionConditionnee = new PossessionConditionnee();
		PossessionConditionnee billet1ObjetPossessionConditionnee = new PossessionConditionnee();
		
		// Init Transformations
		
		// Init ChoixConditionnes
		ChoixConditionne finVendreUnBilletChoixConditionne = new ChoixConditionne();
		
		// Init ActionsConditionnees
		ActionConditionnee composteActionConditionnee = new ActionConditionnee();
		
		// Init Comparaisons
		Comparaison plusPlaisir1Comparaison = new Comparaison();
		Comparaison plusBillet1Comparaison = new Comparaison();
		
		
		/**
		 * Fill all elements
		 */
		// Fill Jeu
		autoTamponneuse.setTerritoire(fete);
		autoTamponneuse.setExplorateur(enfant);
		autoTamponneuse.setDifficulte(Difficulte.moyen);
		
		// Fill Dependencies
		// Fill Objets
		billet1.setQuantite(1);
		billet1.setObjet(billet);
		plaisir1.setQuantite(1);
		plaisir1.setObjet(plaisir);
		
		// Fill PossessionsConditionnees
		plaisir1ObjetPossessionConditionnee.setPossession(plaisir1Objet);
		billet1ObjetPossessionConditionnee.setPossession(billet1Objet);
		
		// Fill Transformations
		
		// Fill ChoixConditionnes
		finVendreUnBilletChoixConditionne.setChoix(finVendre);
		finVendreUnBilletChoixConditionne.addCondition(unBillet);
		
		// Fill ActionsConditionnees
		composteActionConditionnee.setAction(composte);
		composteActionConditionnee.addChoixOffert(finVendreUnBilletChoixConditionne);
		
		// Fill Comparaisons
		plusPlaisir1Comparaison.setComparateur(Comparateur.plus);
		plusPlaisir1Comparaison.setObjet(plaisir1);
		plusBillet1Comparaison.setComparateur(Comparateur.plus);
		plusBillet1Comparaison.setObjet(billet1);
		
		// Fill Composants
		// Fill Territoires
		fete.addComposants(parents);
		fete.addComposants(manege);
		fete.addComposants(maison);
		fete.addComposants(bonheur);
		fete.addComposants(tristesse);
		fete.addComposants(retour);
		
		// Fill Lieux
		manege.addPersonnes(vendeur);
		manege.setPosition(Emplacement.intermediaire);
		maison.setPosition(Emplacement.fin);
		parents.addPossessionConditionnee(billet1ObjetPossessionConditionnee);
		parents.setPosition(Emplacement.depart);
		
		// Fill Chemins
		bonheur.setDepart(parents);
		bonheur.setFin(manege);
		bonheur.setOuverture(Ouverture.ouvert);
		bonheur.setObligation(Obligation.facultatif);
		bonheur.setVisibilite(Visibilite.visible);
		retour.setDepart(parents);
		retour.setFin(maison);
		retour.setOuverture(Ouverture.ouvert);
		retour.addConditionOuverture(unPlaisir);
		retour.setObligation(Obligation.facultatif);
		retour.setVisibilite(Visibilite.visible);
		tristesse.setDepart(manege);
		tristesse.setFin(parents);
		tristesse.setOuverture(Ouverture.ouvert);
		tristesse.setObligation(Obligation.facultatif);
		tristesse.setVisibilite(Visibilite.visible);
		
		// Fill Personnes
		vendeur.setObligation(Obligation.facultatif);
		vendeur.addChoix(vendre);
		
		// Fill Explorateurs
		enfant.setPoidsMax(1);
		
		// Fill Connaissances
		
		// Fill ObjetsElementaires
		plaisir.setVisibilite(Visibilite.visible);
		plaisir.setTransformabilite(Transformabilite.immuable);
		billet.setVisibilite(Visibilite.visible);
		billet.setTransformabilite(Transformabilite.immuable);
		
		// Fill Conditions
		unPlaisir.addComparaison(plusPlaisir1Comparaison);
		unPlaisir.setOperateur(Operateur.et);
		
		unBillet.addComparaison(plusBillet1Comparaison);
		unBillet.setOperateur(Operateur.et);
		
		
		// Fill Choix
		finVendre.setPosition(Emplacement.fin);
		vendre.addAction(composteActionConditionnee);
		vendre.setPosition(Emplacement.depart);
		
		// Fill Actions
		composte.addPossessionConditionnee(plaisir1ObjetPossessionConditionnee);
		composte.addObjetConsomme(billet1);
		

		/**
		 * Launch the game
		 */
		Controleur controleur = new ControleurTexte(new AfficheurTexte(), autoTamponneuse);
		controleur.jouer();
	}

}
