import modele.*;
import afficheurs.*;
import controleurs.*;

public class Grenadine {

	/**
	  * AUTOGENERATED CLASS
	  * Do not modify the code
	  * Please use toJava.mtl inside an Acceleo Project
	  */

	public static void main(String[] args) {
		/**
		 * Init all elements
		 */
		// Init Jeu
		Jeu grenadine = new Jeu("Grenadine");
		// Init Composants
		Territoire maison = new Territoire("Maison");
		Lieu cuisine = new Lieu("Cuisine");
		Lieu salon = new Lieu("Salon");
		Chemin couloir = new Chemin("Couloir");
		Explorateur etudiant = new Explorateur("Etudiant");
		ObjetElementaire verre = new ObjetElementaire("Verre");
		ObjetElementaire eau = new ObjetElementaire("Eau");
		ObjetElementaire sirop = new ObjetElementaire("Sirop");
		ObjetElementaire verreEau = new ObjetElementaire("VerreEau");
		ObjetElementaire verreSirop = new ObjetElementaire("VerreSirop");
		ObjetElementaire verreGrenadine = new ObjetElementaire("VerreGrenadine");
		Condition uneGrenadine = new Condition("UneGrenadine");
		Condition unVerre = new Condition("UnVerre");
		Condition uneEau = new Condition("UneEau");
		Condition unSirop = new Condition("UnSirop");
		Condition unVerreEau = new Condition("UnVerreEau");
		Condition unVerreSirop = new Condition("UnVerreSirop");
		
		// Init Dependencies
		// Init Objets
		Objet verreSirop1 = new Objet();
		Objet verre1 = new Objet();
		Objet verreGrenadine1 = new Objet();
		Objet eau1 = new Objet();
		Objet sirop1 = new Objet();
		Objet verreEau1 = new Objet();
		
		// Init Possessions
		Objet verreSirop1Objet = verreSirop1;
		Objet verre1Objet = verre1;
		Objet verreGrenadine1Objet = verreGrenadine1;
		Objet sirop1Objet = sirop1;
		Objet verreEau1Objet = verreEau1;
		Objet eau1Objet = eau1;
		
		// Init PossessionsConditionnees
		PossessionConditionnee verre1ObjetPossessionConditionnee = new PossessionConditionnee();
		PossessionConditionnee eau1ObjetPossessionConditionnee = new PossessionConditionnee();
		PossessionConditionnee sirop1ObjetPossessionConditionnee = new PossessionConditionnee();
		
		// Init Transformations
		Transformation verreGrenadine1UnSiropTransformation = new Transformation();
		Transformation verreGrenadine1UnVerreSiropTransformation = new Transformation();
		Transformation verreEau1UneEauTransformation = new Transformation();
		Transformation verreSirop1UnSiropTransformation = new Transformation();
		Transformation verreGrenadine1UneEauTransformation = new Transformation();
		
		// Init ChoixConditionnes
		
		// Init ActionsConditionnees
		
		// Init Comparaisons
		Comparaison exactementVerre1Comparaison = new Comparaison();
		Comparaison exactementEau1Comparaison = new Comparaison();
		Comparaison exactementVerreGrenadine1Comparaison = new Comparaison();
		Comparaison exactementSirop1Comparaison = new Comparaison();
		Comparaison exactementVerreSirop1Comparaison = new Comparaison();
		Comparaison exactementVerreEau1Comparaison = new Comparaison();
		
		
		/**
		 * Fill all elements
		 */
		// Fill Jeu
		grenadine.setTerritoire(maison);
		grenadine.setExplorateur(etudiant);
		grenadine.setDifficulte(Difficulte.moyen);
		
		// Fill Dependencies
		// Fill Objets
		verreSirop1.setQuantite(1);
		verreSirop1.setObjet(verreSirop);
		verre1.setQuantite(1);
		verre1.setObjet(verre);
		verreGrenadine1.setQuantite(1);
		verreGrenadine1.setObjet(verreGrenadine);
		eau1.setQuantite(1);
		eau1.setObjet(eau);
		sirop1.setQuantite(1);
		sirop1.setObjet(sirop);
		verreEau1.setQuantite(1);
		verreEau1.setObjet(verreEau);
		
		// Fill PossessionsConditionnees
		verre1ObjetPossessionConditionnee.setPossession(verre1Objet);
		eau1ObjetPossessionConditionnee.setPossession(eau1Objet);
		sirop1ObjetPossessionConditionnee.setPossession(sirop1Objet);
		
		// Fill Transformations
		verreGrenadine1UnSiropTransformation.addObjet(verreGrenadine1);
		verreGrenadine1UnSiropTransformation.addCondition(unSirop);
		verreGrenadine1UnVerreSiropTransformation.addObjet(verreGrenadine1);
		verreGrenadine1UnVerreSiropTransformation.addCondition(unVerreSirop);
		verreEau1UneEauTransformation.addObjet(verreEau1);
		verreEau1UneEauTransformation.addCondition(uneEau);
		verreSirop1UnSiropTransformation.addObjet(verreSirop1);
		verreSirop1UnSiropTransformation.addCondition(unSirop);
		verreGrenadine1UneEauTransformation.addObjet(verreGrenadine1);
		verreGrenadine1UneEauTransformation.addCondition(uneEau);
		
		// Fill ChoixConditionnes
		
		// Fill ActionsConditionnees
		
		// Fill Comparaisons
		exactementVerre1Comparaison.setComparateur(Comparateur.exactement);
		exactementVerre1Comparaison.setObjet(verre1);
		exactementEau1Comparaison.setComparateur(Comparateur.exactement);
		exactementEau1Comparaison.setObjet(eau1);
		exactementVerreGrenadine1Comparaison.setComparateur(Comparateur.exactement);
		exactementVerreGrenadine1Comparaison.setObjet(verreGrenadine1);
		exactementSirop1Comparaison.setComparateur(Comparateur.exactement);
		exactementSirop1Comparaison.setObjet(sirop1);
		exactementVerreSirop1Comparaison.setComparateur(Comparateur.exactement);
		exactementVerreSirop1Comparaison.setObjet(verreSirop1);
		exactementVerreEau1Comparaison.setComparateur(Comparateur.exactement);
		exactementVerreEau1Comparaison.setObjet(verreEau1);
		
		// Fill Composants
		// Fill Territoires
		maison.addComposants(cuisine);
		maison.addComposants(salon);
		maison.addComposants(couloir);
		
		// Fill Lieux
		salon.setPosition(Emplacement.fin);
		cuisine.addPossessionConditionnee(verre1ObjetPossessionConditionnee);
		cuisine.addPossessionConditionnee(eau1ObjetPossessionConditionnee);
		cuisine.addPossessionConditionnee(sirop1ObjetPossessionConditionnee);
		cuisine.setPosition(Emplacement.depart);
		
		// Fill Chemins
		couloir.setDepart(cuisine);
		couloir.setFin(salon);
		couloir.setOuverture(Ouverture.ouvert);
		couloir.setObligation(Obligation.obligatoire);
		couloir.setVisibilite(Visibilite.visible);
		couloir.addConditionVisibilite(uneGrenadine);
		
		// Fill Personnes
		
		// Fill Explorateurs
		etudiant.setPoidsMax(2);
		
		// Fill Connaissances
		
		// Fill ObjetsElementaires
		verre.setVisibilite(Visibilite.visible);
		verre.setTransformabilite(Transformabilite.transformable);
		verre.addConditionTransformabilite(verreEau1UneEauTransformation);
		verre.addConditionTransformabilite(verreSirop1UnSiropTransformation);
		verre.addConditionTransformabilite(verreGrenadine1UnVerreSiropTransformation);
		verreEau.setVisibilite(Visibilite.visible);
		verreEau.setTransformabilite(Transformabilite.transformable);
		verreEau.addConditionTransformabilite(verreGrenadine1UnSiropTransformation);
		verreGrenadine.setVisibilite(Visibilite.visible);
		verreGrenadine.setTransformabilite(Transformabilite.immuable);
		eau.setVisibilite(Visibilite.visible);
		eau.setTransformabilite(Transformabilite.transformable);
		verreSirop.setVisibilite(Visibilite.visible);
		verreSirop.setTransformabilite(Transformabilite.transformable);
		verreSirop.addConditionTransformabilite(verreGrenadine1UneEauTransformation);
		sirop.setVisibilite(Visibilite.visible);
		sirop.setTransformabilite(Transformabilite.transformable);
		
		// Fill Conditions
		unVerre.addComparaison(exactementVerre1Comparaison);
		unVerre.setOperateur(Operateur.et);
		
		uneEau.addComparaison(exactementEau1Comparaison);
		uneEau.setOperateur(Operateur.et);
		
		unVerreEau.addComparaison(exactementVerreEau1Comparaison);
		unVerreEau.setOperateur(Operateur.et);
		
		unVerreSirop.addComparaison(exactementVerreSirop1Comparaison);
		unVerreSirop.setOperateur(Operateur.et);
		
		uneGrenadine.addComparaison(exactementVerreGrenadine1Comparaison);
		uneGrenadine.setOperateur(Operateur.et);
		
		unSirop.addComparaison(exactementSirop1Comparaison);
		unSirop.setOperateur(Operateur.et);
		
		
		// Fill Choix
		
		// Fill Actions
		

		/**
		 * Launch the game
		 */
		Controleur controleur = new ControleurTexte(new AfficheurTexte(), grenadine);
		controleur.jouer();
	}

}
