import modele.*;
import afficheurs.*;
import controleurs.*;

public class JeuEnigme2 {

	/**
	  * AUTOGENERATED CLASS
	  * Do not modify the code
	  * Please use toJava.mtl inside an Acceleo Project
	  */

	public static void main(String[] args) {
		/**
		 * Init all elements
		 */
		// Init Jeu
		Jeu jeuEnigme2 = new Jeu("JeuEnigme2");
		// Init Composants
		Territoire enonce = new Territoire("Enonce");
		Lieu debut = new Lieu("Debut");
		Lieu succes = new Lieu("Succes");
		Lieu echec = new Lieu("Echec");
		Lieu enigme = new Lieu("Enigme");
		Chemin initialisation = new Chemin("Initialisation");
		Chemin bonChemin = new Chemin("BonChemin");
		Chemin mauvaisChemin = new Chemin("MauvaisChemin");
		ObjetElementaire tentative = new ObjetElementaire("Tentative");
		Connaissance reussite = new Connaissance("Reussite");
		Explorateur joueur = new Explorateur("Joueur");
		Personne sphinx = new Personne("Sphinx");
		Choix question = new Choix("Question");
		Choix finQuestion = new Choix("FinQuestion");
		Action bonneReponse = new Action("BonneReponse");
		Action mauvaiseReponse = new Action("MauvaiseReponse");
		Decision bonneFin = new Decision("BonneFin");
		Condition mauvaiseFin = new Condition("MauvaiseFin");
		Condition premiereQuestion = new Condition("PremiereQuestion");
		Condition encoreTentative = new Condition("EncoreTentative");
		
		// Init Dependencies
		// Init Objets
		Objet tentative3 = new Objet();
		Objet tentative1 = new Objet();
		
		// Init Possessions
		Objet tentative3Objet = tentative3;
		Possession reussitePossession = reussite;
		Objet tentative1Objet = tentative1;
		
		// Init PossessionsConditionnees
		PossessionConditionnee tentative3ObjetPossessionConditionnee = new PossessionConditionnee();
		PossessionConditionnee reussitePossessionPossessionConditionnee = new PossessionConditionnee();
		
		// Init Transformations
		
		// Init ChoixConditionnes
		ChoixConditionne finQuestionChoixConditionne = new ChoixConditionne();
		ChoixConditionne finQuestionMauvaiseFinChoixConditionne = new ChoixConditionne();
		ChoixConditionne questionEncoreTentativeChoixConditionne = new ChoixConditionne();
		
		// Init ActionsConditionnees
		ActionConditionnee mauvaiseReponseActionConditionnee = new ActionConditionnee();
		ActionConditionnee bonneReponseEncoreTentativeActionConditionnee = new ActionConditionnee();
		
		// Init Comparaisons
		Comparaison exactementTentative3Comparaison = new Comparaison();
		Comparaison plusTentative1Comparaison = new Comparaison();
		
		
		/**
		 * Fill all elements
		 */
		// Fill Jeu
		jeuEnigme2.setTerritoire(enonce);
		jeuEnigme2.setExplorateur(joueur);
		jeuEnigme2.setDifficulte(Difficulte.facile);
		
		// Fill Dependencies
		// Fill Objets
		tentative3.setQuantite(3);
		tentative3.setObjet(tentative);
		tentative1.setQuantite(1);
		tentative1.setObjet(tentative);
		
		// Fill PossessionsConditionnees
		tentative3ObjetPossessionConditionnee.setPossession(tentative3Objet);
		reussitePossessionPossessionConditionnee.setPossession(reussitePossession);
		
		// Fill Transformations
		
		// Fill ChoixConditionnes
		finQuestionChoixConditionne.setChoix(finQuestion);
		finQuestionMauvaiseFinChoixConditionne.setChoix(finQuestion);
		finQuestionMauvaiseFinChoixConditionne.addCondition(mauvaiseFin);
		questionEncoreTentativeChoixConditionne.setChoix(question);
		questionEncoreTentativeChoixConditionne.addCondition(encoreTentative);
		
		// Fill ActionsConditionnees
		mauvaiseReponseActionConditionnee.setAction(mauvaiseReponse);
		mauvaiseReponseActionConditionnee.addChoixOffert(questionEncoreTentativeChoixConditionne);
		mauvaiseReponseActionConditionnee.addChoixOffert(finQuestionMauvaiseFinChoixConditionne);
		bonneReponseEncoreTentativeActionConditionnee.setAction(bonneReponse);
		bonneReponseEncoreTentativeActionConditionnee.addCondition(encoreTentative);
		bonneReponseEncoreTentativeActionConditionnee.addChoixOffert(finQuestionChoixConditionne);
		
		// Fill Comparaisons
		exactementTentative3Comparaison.setComparateur(Comparateur.exactement);
		exactementTentative3Comparaison.setObjet(tentative3);
		plusTentative1Comparaison.setComparateur(Comparateur.plus);
		plusTentative1Comparaison.setObjet(tentative1);
		
		// Fill Composants
		// Fill Territoires
		enonce.addComposants(debut);
		enonce.addComposants(succes);
		enonce.addComposants(echec);
		enonce.addComposants(enigme);
		enonce.addComposants(initialisation);
		enonce.addComposants(bonChemin);
		enonce.addComposants(mauvaisChemin);
		
		// Fill Lieux
		enigme.addPersonnes(sphinx);
		enigme.setPosition(Emplacement.intermediaire);
		succes.setPosition(Emplacement.fin);
		echec.setPosition(Emplacement.fin);
		debut.setPosition(Emplacement.depart);
		
		// Fill Chemins
		mauvaisChemin.setDepart(enigme);
		mauvaisChemin.setFin(echec);
		mauvaisChemin.setOuverture(Ouverture.ouvert);
		mauvaisChemin.setObligation(Obligation.obligatoire);
		mauvaisChemin.setVisibilite(Visibilite.visible);
		mauvaisChemin.addConditionVisibilite(mauvaiseFin);
		initialisation.setDepart(debut);
		initialisation.setFin(enigme);
		initialisation.setOuverture(Ouverture.ouvert);
		initialisation.setObligation(Obligation.facultatif);
		initialisation.setVisibilite(Visibilite.visible);
		bonChemin.setDepart(enigme);
		bonChemin.setFin(succes);
		bonChemin.setOuverture(Ouverture.ouvert);
		bonChemin.setObligation(Obligation.obligatoire);
		bonChemin.setVisibilite(Visibilite.visible);
		bonChemin.addConditionVisibilite(bonneFin);
		
		// Fill Personnes
		sphinx.setObligation(Obligation.obligatoire);
		sphinx.addChoix(question);
		
		// Fill Explorateurs
		joueur.addPossessionConditionnee(tentative3ObjetPossessionConditionnee);
		joueur.setPoidsMax(3);
		
		// Fill Connaissances
		reussite.setVisibilite(Visibilite.visible);
		
		// Fill ObjetsElementaires
		tentative.setVisibilite(Visibilite.visible);
		tentative.setTransformabilite(Transformabilite.immuable);
		
		// Fill Conditions
		mauvaiseFin.addCondition(bonneFin);
		mauvaiseFin.setOperateur(Operateur.non);
		
		bonneFin.setOperateur(Operateur.et);
		
		encoreTentative.addComparaison(plusTentative1Comparaison);
		encoreTentative.setOperateur(Operateur.et);
		
		premiereQuestion.addComparaison(exactementTentative3Comparaison);
		premiereQuestion.setOperateur(Operateur.et);
		
		
		// Fill Choix
		finQuestion.setPosition(Emplacement.fin);
		question.addAction(bonneReponseEncoreTentativeActionConditionnee);
		question.addAction(mauvaiseReponseActionConditionnee);
		question.setPosition(Emplacement.depart);
		question.addCondition(premiereQuestion);
		
		// Fill Actions
		bonneReponse.addPossessionConditionnee(reussitePossessionPossessionConditionnee);
		mauvaiseReponse.addObjetConsomme(tentative1);
		

		/**
		 * Launch the game
		 */
		Controleur controleur = new ControleurTexte(new AfficheurTexte(), jeuEnigme2);
		controleur.jouer();
	}

}
