/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.tests;

import com.google.inject.Inject;
import fr.enseeiht.tests.PDL2InjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(PDL2InjectorProvider.class)
@SuppressWarnings("all")
public class PDL2ParsingTest {
  @Inject
  private ParseHelper<fr.enseeiht.pDL2.Process> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final fr.enseeiht.pDL2.Process result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
