/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.simplepdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SimplePDLDSLStandaloneSetup extends SimplePDLDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new SimplePDLDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
