package test;

import modele.*;
import afficheurs.*;
import controleurs.*;

public class PileOuFace {

	/**
	  * AUTOGENERATED CLASS
	  * Do not modify the code
	  * Please use toJava.mtl inside an Acceleo Project
	  */

	public static void main(String[] args) {
		/**
		 * Init all elements
		 */
		// Init Jeu
		Jeu pileOuFace = new Jeu("PileOuFace");
		// Init Dependencies
		// Init Objets
		
		// Init Possessions
		
		// Init PossessionsConditionnees
		
		// Init Transformations
		
		// Init ChoixConditionnes
		
		// Init ActionsConditionnees
		
		// Init Comparaisons
		
		// Init Composants
		Territoire rue = new Territoire("Rue");
		Lieu interpelation = new Lieu("Interpelation");
		Lieu richesse = new Lieu("Richesse");
		Lieu ruine = new Lieu("Ruine");
		Chemin pile = new Chemin("Pile");
		Chemin face = new Chemin("Face");
		Explorateur passant = new Explorateur("Passant");
		Condition lance = new Condition("Lance");
		
		
		/**
		 * Fill all elements
		 */
		// Fill Jeu
		pileOuFace.setTerritoire(rue);
		pileOuFace.setExplorateur(passant);
		pileOuFace.setDifficulte(Difficulte.moyen);
		
		// Fill Dependencies
		// Fill Objets
		
		// Fill PossessionsConditionnees
		
		// Fill Transformations
		
		// Fill ChoixConditionnes
		
		// Fill ActionsConditionnees
		
		// Fill Comparaisons
		
		// Fill Composants
		// Fill Territoires
		rue.addComposants(interpelation);
		rue.addComposants(richesse);
		rue.addComposants(ruine);
		rue.addComposants(pile);
		rue.addComposants(face);
		
		// Fill Lieux
		interpelation.setPosition(Emplacement.depart);
		ruine.setPosition(Emplacement.fin);
		richesse.setPosition(Emplacement.fin);
		
		// Fill Chemins
		pile.setDepart(interpelation);
		pile.setFin(richesse);
		pile.setOuverture(Ouverture.ouvert);
		pile.setObligation(Obligation.obligatoire);
		pile.setVisibilite(Visibilite.visible);
		pile.addConditionVisibilite(lance);
		face.setDepart(interpelation);
		face.setFin(ruine);
		face.setOuverture(Ouverture.ouvert);
		face.setObligation(Obligation.facultatif);
		face.setVisibilite(Visibilite.visible);
		
		// Fill Personnes
		
		// Fill Explorateurs
		passant.setPoidsMax(0);
		
		// Fill Connaissances
		
		// Fill ObjetsElementaires
		
		// Fill Conditions
		lance.setOperateur(Operateur.et);
		lance.setProbabilite(50);
		
		// Fill Choix
		
		// Fill Actions
		

		/**
		 * Launch the game
		 */
		Controleur controleur = new ControleurTexte(new AfficheurTexte(), pileOuFace);
		controleur.jouer();
	}

}
