/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.ui.contentassist;

import fr.enseeiht.ui.contentassist.AbstractPDL2ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PDL2ProposalProvider extends AbstractPDL2ProposalProvider {
}
